version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver --settings=core.dev_settings 0.0.0.0:8000
    volumes:
      - .:/mymdb
    ports:
      - 8000:8000
    env_file:
      - ./.env
